//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp_SmsServiseFeedBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmPhone
    {
        public int id { get; set; }
        public string AspNetUser_ID { get; set; }
        public string Phone { get; set; }
        public bool Status { get; set; }
    }
}
