//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp_SmsServiseFeedBack
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_A4A060_csEntities : DbContext
    {
        public DB_A4A060_csEntities()
            : base("name=DB_A4A060_csEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Farm_Alert_Rules> Farm_Alert_Rules { get; set; }
        public virtual DbSet<FarmCow> FarmCows { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<SmsLog> SmsLogs { get; set; }
        public virtual DbSet<Z_AlertLogs> Z_AlertLogs { get; set; }
        public virtual DbSet<FarmPhone> FarmPhones { get; set; }
    
        public virtual ObjectResult<SMS_Get_PhonesListByUserID_Result> SMS_Get_PhonesListByUserID(string user_id_list)
        {
            var user_id_listParameter = user_id_list != null ?
                new ObjectParameter("user_id_list", user_id_list) :
                new ObjectParameter("user_id_list", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SMS_Get_PhonesListByUserID_Result>("SMS_Get_PhonesListByUserID", user_id_listParameter);
        }
    
        public virtual ObjectResult<SMS_GetZ_AlertLogsByDate_Result> SMS_GetZ_AlertLogsByDate(Nullable<System.DateTime> dt)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SMS_GetZ_AlertLogsByDate_Result>("SMS_GetZ_AlertLogsByDate", dtParameter);
        }
    }
}
