//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp_SmsServiseFeedBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsLog
    {
        public int id { get; set; }
        public string @event { get; set; }
        public string message { get; set; }
        public string phonenumber { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> datemark { get; set; }
        public string smscId { get; set; }
        public string AspNetUser_Id { get; set; }
    }
}
